### ISSUE TITLE
possibly revert https://github.com/smfrpc/smf/pull/287

### ISSUE THREAD

**Issue by senior7515** [smfrpc/smf#288]
we should keep compatibility w/ flatc generator.

**Comment by crackcomm** [comment]
what is the problem? ^^

**Comment by crackcomm** [comment]
I tested it with CMake

```cmake
smfc_gen(
  GOLANG
  TARGET_NAME not_a_demo
  OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}/apps
  SOURCES not_a_demo.fbs)
```

**Comment by senior7515** [comment]
@crackcomm  

so flatc/smfc should be the consistent. Even if it means consistently incorrect.

flatc generates one subdirectory per sub import in go. 

i..e: 
`package foo.bar.baz`

will create a folder in `foo/bar/baz.go` where baz.go will have `package baz` at the top. 

Same w/ smfc.
