### ISSUE TITLE
Has the WAL code been dropped?

### ISSUE THREAD

**Issue by erichocean** [smfrpc/smf#297]
I'm coming back to this project after about a year off (maybe more—time flies) and it seems like the WAL-related code is gone? Either that or I'm blind…

**Comment by senior7515** [comment]
yeah, i narrowed the scope to RPC + multilang (go is in the works). 


Please check this out. Seastar has basically most of the structure that you'll need. 

https://github.com/scylladb/seastar/blob/2ec0a04396e018b257f40c73a8261c5177eae60d/include/seastar/core/iostream-impl.hh

As you write one, you'll realize just how big that project is :)

**Comment by senior7515** [comment]
note you can still use the code generator from here to be the base of your WAL if you wanna use flatbuffers.
