### ISSUE TITLE
The build process not build dependencies during the configuration phase

### ISSUE THREAD

**Issue by nacl** [smfrpc/smf#316]
The current build system will, upon a simple `cmake` invocation for build configuration, will attempt to compile and install all third-party library dependencies.  This behavior is usually not expected or desired.

This is intended to be a [temporary state](https://github.com/smfrpc/smf/pull/314#issuecomment-467251369) as the build process is refined.  While this is happening, though, it would be convenient if dependency fetching is turned off by default so that developers are not surprised by the build process.

This may be completed as a part of merging in #314.

**Comment by senior7515** [comment]
@nacl  - wanna put up a patch for docs & this simple default?

**Comment by senior7515** [comment]
now that #317 & #314  are merged this should be pretty easy.

**Comment by nacl** [comment]
Unfortunately, I'm not going to be able to do this until I get authorization from my employer to transfer copyright of the output to me personally.   I don't know how long that will take, so you may want to take care of this yourself.

**Comment by senior7515** [comment]
@nacl  - sounds good. I'm going to patch this today. let me know. 

btw there are a few patches during shutdown that you might want to pull in to your repo.
