### ISSUE TITLE
install-deps.sh should not change the system compiler on Ubuntu 16.04

### ISSUE THREAD

**Issue by nacl** [smfrpc/smf#334]
**Describe the bug**
On Ubuntu 16.04 `install-deps.sh` script changes the default system compiler in the alternatives database.  This is not expected behavior for a dependency installation script, which should only make the software available, not change any other system configuration.

The script also clobbers sections of the the alternatives database, which makes it difficult to restore the original system state.  The changes to the alternatives database are a bit heavy-handed, and should be made more refined.

**To Reproduce**
1. Invoke install-deps.sh as root
2. `gcc -version` identifies itself as `gcc-8`, despite it being `gcc-5` earlier.

**Expected behavior**

`gcc -version` to identify itself as whatever the user previously had set.  The alternatives list should also not be modified.

**Environment Info**
- Ubuntu 16.04
- git b052af2 (although the offending code is still present)

**Comment by senior7515** [comment]
That's a fair request. We'll fix it. We need it for our CI. So we just need to test if the CI variable is set.

**Comment by senior7515** [comment]
We should also test for cmake version in `ubuntu::Xenial` just in case it is also installed out of band with this fix.

**Comment by senior7515** [comment]
@nacl  should be up on the latest revision.
