### ISSUE TITLE
always generate output file even if empty

### ISSUE THREAD

**Issue by senior7515** [smfrpc/smf#340]
smfc_generator() cmake function should always generate a file, even if empty.

calling `ninja -v -d explain` returns the reason why targets are built or not w/ ninja. 

If we don't generate the file, the ninja always runs and does unnecessary work which compounds on transitive builds like redpanda to re-build files not needed.

**Comment by noahdesu** [comment]
It might be useful to create a special label to track issues that might be worth looking at again in the future. Like this one.

**Comment by senior7515** [comment]
@noahdesu  - done. added `REVISIT`
