### ISSUE TITLE
feature: upgrade seastar api to v6

### ISSUE THREAD

**Issue by lumontec** [smfrpc/smf#374]
**Upgrade seastar api to v6 version.**

Api migration will follow the line of: 
[https://github.com/vectorizedio/redpanda](https://github.com/vectorizedio/redpanda).
Progress tracked on: 
[https://github.com/lumontec/smf/tree/feature/upgrade_seastar_api_v6](https://github.com/lumontec/smf/tree/feature/upgrade_seastar_api_v6)

**Comment by lumontec** [comment]
@senior7515 let me know if you prefer to open a branch here otherwise I will simply merge my fork when I am done.

**Comment by senior7515** [comment]
@lumontec i think a pull request from your branch is perfect.

**Comment by lumontec** [comment]
Hey @senior7515 I looked at the code back and forth but it seems that the only function that required an actual migration was **make_file_output_stream()** which now returns a future. Let me know if I missed something !

**Comment by senior7515** [comment]
@lumontec i just gave you a review. only minor things. Yeah, API=6 was about filesystem changes. 

but fantastic that you updated the build tree there too! such a fantastic improvement. thank you so much!
