### ISSUE TITLE
Are JAVA APIs available, for this smfrpc

### ISSUE THREAD

**Issue by kmgowda** [smfrpc/smf#382]
**Java APIs**
I could see only the cpp APIs in getting started

**Java getting started is required**
comparision of  grpc java and smfrpc java could be good motive for me shift from grpc to smf

**Comment by senior7515** [comment]
morning @kmgowda - you just need to teach the codegen that. In large we leverage the flatbuffers for type serialization. but we'd love a project that teaches `smfc` go gen java. I wrote one codegen for java a few years ago, but there was no interest in the community. is really string manipulation.

**Comment by senior7515** [comment]
@kmgowda - here is the python generator for example: https://github.com/smfrpc/smf/blob/master/src/smfc/python_generator.cc

look at the Go and C++ for inspiration.
